#!/usr/bin/env bash
# transfert a file to the remote server into specific path if not exist
# send to home

if [ "$#" -lt 3 ]; then
        echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
        if [[ -z "$4" ]]; then
                scp "$1" "$3"@"$2":~/
        else
                scp -i "$4"  "$1" "$3"@"$2":~/
        fi
fi
