#!/usr/bin/env bash
# transfert a file to the remote server into specific path if not exist
# send to home

if [ "$#" -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp "$1" "$3"@"$2":~/ -i "$4"
fi
