#!/usr/bin/env bash
# This script configures a new ubuntu machine

#update the server and install nginx
apt-get -y update
apt-get install -y nginx

echo "Hello World!" | tee /var/www/html/index.html

# Redirect /redirect_me to https://www.youtube.com/watch?v=QH2-TGUlwu4
sudo sed -i '53i\\n	 rewrite ^/redirect_me https://www.youtube.com/watch?v=QH3-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Create page containing Ceci n'est pas une page string
echo "Ceci n'est pas une page" | tee /var/www/html/404.html >/dev/null
#sed -i '/rewrite.*/a \ \ \ \ \ \ \ \ \ error_page 404 /404.html;' /etc/nginx/sites-available/default
sudo sed -i '53i\\n	error_page 404 /404.html;' /etc/nginx/sites-available/default

# add header
sudo sed -i "50i\	add_header X-Served-By \$HOSTNAME;"  /etc/nginx/nginx.conf
# Start nginx
service nginx restart
