#!/usr/bin/env bash
# installs and configures HAProxy

#the installation
sudo apt-get -y update
sudo apt-get -y install haproxy

# configuration
echo "
frontend www
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server 350312-web-01 34.232.68.194:80 check
    server 350312-web-02 54.173.210.20:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

# starting the service
sudo service haproxy restart
