#!/usr/bin/env bash
# installs and configures HAProxy

#the installation
sudo apt-get -y update
sudo apt-get -y install haproxy

# configuration
echo "
frontend www
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server 125647-web-01 34.229.161.215:80 check
    server 125647-web-02 54.146.90.232:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

# starting the service
sudo service haproxy restart
