#!/usr/bin/env bash
# This script installs and configures HAproxy on your lb-01 server.

# Update and install haproxy
apt-get install -y --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.8
apt-get install -y haproxy=2.8.\*

# Create copy of the original configuration
cp -a /etc/haproxy/haproxy.cfg{,.orig}

# Create configuration
configuration="
frontend main
        bind *:80
	default_backend web_servers
	
backend web_servers
	balance roundrobin
	server 465573-web-01 3.80.19.87:80 check
	server 465573-web-02 100.26.142.144:80 check
"
printf %s "$configuration" >> /etc/haproxy/haproxy.cfg

service haproxy restart

# Enable HAproxy init script
update-rc.d haproxy defaults
