#!/usr/bin/env bash
# create a file

touch /var/run/myscript.pid
pid=$(pgrep -f  /var/run/myscript.pid)
echo "$pid" > /var/run/myscript.pid

trap "rm /var/run/myscript.pid; kill -9  100-process_and_pid_file" SIGQUIT
trap "echo I hate the kill command" SIGTERM
trap "echo Y U no love me?!" SIGINT SIGTERM

while true
do
        echo "To infinity and beyond"
        sleep 2
done
