#!/usr/bin/env bash
# create a file
# shellcheck disable=SC2009

echo $$ > /var/run/myscript.pid

trap "rm /var/run/myscript.pid; exit;" SIGQUIT SIGTERM
trap "echo 'I hate the kill command'" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT

while true
do
        echo "To infinity and beyond"
        sleep 2
done
