#!/usr/bin/env bash
# bash script that stop 4-to_infinity_add_beyound process
# shellcheck disable=SC2009

pid=$(ps aux | grep 4-to_infinity_and_beyond  | grep -v grep | awk '{print $2}')
pkill "$pid"
