#!/usr/bin/env bash
# red the content of a file

IFS=$'\n'

while read -r line
do
	usename=$(echo "$line" | cut -d ':' -f1)
	uid=$(echo "$line" | cut -d ':' -f3)
	homedir=$(echo "$line" | cut -d ':' -f6)
	echo "$username:$uid:$homedir"
done < /etc/passwd
