#!/usr/bin/env bash
# get the element of from the user and put them as entended

IFS=$':'

while read -r line
do
	user=$( echo "$line" | cut -d ':' -f 1 )
	password=$( echo "$line" | cut -d ':' -f 2 )
	user_id=$( echo "$line" | cut -d ':' -f 3 )
	group_id=$( echo "$line" | cut -d ':' -f 4 )
	user_id_info=$( echo "$line" | cut -d ':' -f 5 )
	home_directory=$( echo "$line" | cut -d ':' -f 6 )
	command_shell=$( echo "$line" | cut -d ':' -f 7 )
	echo "The user $user is part of the $group_id gang, lives in $home_directory and rides $command_shell. $user_id's place is protected by the passcode $password, more info about the user here: $user_id_info"
done < /etc/passwd
