#!/usr/bin/env bash
# print "bad luck" at 4 loop, "good luck" at 8 loop
# otherwise print "Best School"

i=1

while [ $i -le 10 ]
do
	if [ $i == 4 ]; then
		echo "bad luck"
	elif [ $i == 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
