#!/usr/bin/env bash
# display 4 and then "bad luck from china"
# diplay 9 and then "bad luck from Japan"
# display 17 and then "bad luck from Italy"

i=1

while [ $i -le 20 ]
do
	echo $i
	case $i in
		4) echo "bad luck from China";;
		9) echo "bad luck from Japan";;
		17) echo "bad luck from Italy";;
	esac
	((i++))
done
