#!/usr/bin/env bash
# display 4 and then "bad luck from china"
# diplay 9 and then "bad luck from Japan"
# display 17 and then "bad luck from Italy"

i=1

while [ $i -le 20 ]
do
	echo $i
	if [ $i -eq 4 ];then
		echo "bad luck from China"
	elif [ $i -eq 9 ];then
		echo "bad luck from Japan"
	elif [ $i -eq 17 ];then
		echo "bad luck from Italy"
	fi
	((i++))
done
