#!/usr/bin/env bash
# display hours from 0 12
# display minutes from 1 to 59

hours=0
minutes=1

while [ $hours -le 12 ]
do
	echo "Hour: $hours"
	while [ $minutes -le 59 ]
	do
		echo "$minutes"
		((minutes++))
	done
	((hours++))
	((minutes=1))
done
