#!/usr/bin/env bash
# change the  hosts file
cp /etc/hosts	/etc/hosts.old
cp /etc/hosts	~/hosts.new
sed -i '/127.0.0.1.*$/c\127.0.0.2 localhost' ~/hosts.new
sed -i '/.*facebook.com$/c\8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
