#!/usr/bin/env bash
# change the  hosts file
cp /etc/hosts	/etc/hosts.old
cp /etc/hosts	~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/g' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
rm ~/hosts.new
