#! /usr/bin/env bash
# Bash Script that accepts 1 argument and runs the 'whoami' command with the passed argument as the user
if [ $# -eq 0 ]; then
	whoami
	exit 0
fi
su - "$1" -s /bin/bash -c 'whoami'
